# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-25 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20190219_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.PositiveIntegerField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=20, default=0.0, max_digits=20)),
                ('subtotal', models.DecimalField(decimal_places=20, default=0.0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
