# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-26 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_charges',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
    ]
