# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-26 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cart_delivery_charges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='delivery_charges',
        ),
    ]
