# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-04 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_auto_20190226_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=False),
        ),
    ]
