# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-19 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=30, unique=True, verbose_name='Category'),
        ),
    ]
