# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-11 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190211_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='No Description'),
        ),
    ]
