# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-16 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190216_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Size'),
        ),
    ]
