# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-13 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190211_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
