# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-13 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190213_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='upload',
            field=models.FileField(default='media_root/image_not_available.jpg', upload_to='uploads/'),
        ),
    ]
