# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-13 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190213_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='upload',
            field=models.FileField(default='image_not_available.jpg', upload_to='uploads/'),
        ),
    ]
